server:
  port: 9871

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

spring:
  kafka:
    properties:
      allow.auto.create.topics: false
      auto.offset.reset: earliest
      schema.registry.url: http://127.0.0.1:8181
    consumer:
      group-id: member-app
      enable-auto-commit: false
      auto-commit-interval: 0
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        specific.avro.reader: true
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://127.0.0.1:8181
      client-id: member-app

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    naming-strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
  flyway:
    enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

member:
  kafka:
    member:
      topicname: public.association.memberservice.member
    address:
      topicname: public.association.memberservice.address
  datastore:
    viewstore:
      url: http://localhost:9874/memberserviceview/
